### ISSUE TITLE
Ser can we play this online?

### ISSUE THREAD

**Issue by nguyend-nam** [DecSP/AirHockey#1]
I don't want to download but still want to play

**Comment by nguyend-nam** [comment]
Ser do not ignore me

**Comment by nguyend-nam** [comment]
Hello ser u still here?

**Comment by jamesngn** [comment]
Good morning Ser, I just want to download it but doesn't want to play it. Bye Ser!

**Comment by nguyend-nam** [comment]
> Good morning Ser, I just want to download it but doesn't want to play it. Bye Ser!

u so lit ser 👀

**Comment by DecSP** [comment]
@nguyend-nam  @jamesngn  can play here https://decsp.github.io/AirHockey/
